language: node_js

sudo: false

install:
  - node -v
  - which node
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  - npm install --ignore-scripts
  - neon clean && neon build

before_script:
  - npm test

script:
  - ./scripts/publish.sh --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")

matrix:
  include:
    - os: linux
      env: BUILDTYPE=release
      node_js: 6

    - os: osx
      osx_image: xcode9.2
      env: BUILDTYPE=release
      node_js: 6
